# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
