# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_auto_20161217_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
