# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0004_auto_20161217_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
