# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20161217_2358'),
        ('inout', '0005_auto_20161218_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=3)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RFIDtag')),
            ],
        ),
    ]
