# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0006_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='action_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 1, 2, 0, 45, 28, 191789, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='structure',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='inout.Structure'),
            preserve_default=False,
        ),
    ]
