# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0008_auto_20170102_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='type',
            new_name='entry_type',
        ),
    ]
