# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160720_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 19, 22, 56, 2, 32542, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
