# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160803_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='qrcode',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='QRcode',
        ),
    ]
