# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160804_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='qrcode',
            field=models.CharField(max_length=1000, null=True, unique=True, verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
