# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160804_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfidtag',
            options={'verbose_name': 'RFID tag', 'verbose_name_plural': 'RFID tags'},
        ),
        migrations.AlterField(
            model_name='item',
            name='qrcode',
            field=models.CharField(blank=True, default=datetime.datetime(2016, 8, 4, 23, 50, 59, 184075, tzinfo=utc), max_length=1000, verbose_name='QR Code'),
            preserve_default=False,
        ),
    ]
