# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160805_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qrcode',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QR Code'),
        ),
    ]
