# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160807_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
