# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160816_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'verbose_name': 'Barcode', 'verbose_name_plural': 'Barcodes'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
